source 'https://rubygems.org'

gem 'berkshelf', '~> 4.3.5'
gem 'chef', '~> 12.19.0'
gem 'chef-dk', '~> 1.2.22'
gem 'chef-provisioning', '~> 2.1.1'
gem 'cookstyle', '~> 1.3.0'
gem 'foodcritic', '~> 7.1.0'
gem 'kitchen-docker', '~> 2.5'
gem 'test-kitchen', '~> 1.11'
gem 'knife-supermarket'
