name 'mysql-resources'
maintainer 'Marc MILLIEN'
maintainer_email 'marc.millien@gmail.com'
license 'all_rights'
description 'Installs/Configures mysql resources'
long_description 'Installs and configures mysql users, databases and user rights'
version '0.1.1'

issues_url 'https://github.com/marcmillien/mysql-resources-chef-cookbook/issues'
source_url 'https://github.com/marcmillien/mysql-resources-chef-cookbook'
